### ISSUE TITLE
Is the project still maintained?

### ISSUE THREAD

**Issue by houmie** [robertmryan/SimplePing#2]
Hello,

This seems like a great idea. Is this project still maintained and safe to be used with Xcode 15?

Thanks,
Houman

**Comment by robertmryan** [comment]
@houmie 

No, this was a one-time conversion in response to some random StackOverflow question.

That having been said, I've just updated it so it compiles with Xcode 15. The only thing you need is to provide your own bundle identifier for the iOS build.

**Comment by houmie** [comment]
Thank you. I just tested it and it works. It's quite difficult finding a Ping project in Swift that also works for IP addresses.  The one I was using so far only works for when pinging hostnames. But yours works also with IP addresses. 👍🏼 

A shame that there seem to be no way to tell it to ping it only once, instead of a endless loop. But I can work around it.

Thanks
